- name: Install System Packages 1 (build-essential, cmake)
  become: true
  apt:
    name: ["build-essential", "cmake"]
  tags:
    - install
    - core

- name: Install System Packages 2 (the rest)
  become: true
  apt:
    name: [ "curl", "htop" ]
  tags:
    - install
    - core
